#! /bin/bash

echo "[*] Integer Comparison [*]"
echo
echo "- is equal to (-eq)"
echo "  >> if [ "$a" -eq "$b" ]"
echo "- is not equal to (-ne)"
echo "  >> if [ "$a" -ne "$b" ]"
echo "- is greater than (-gt) / (>)"
echo "  >> if [ "$a" -gt "$b" ]"
echo "  >> if [ "$a" > "$b" ]"
echo "  >> (("$a" > "$b"))"
echo "- is greater than or equal to (-ge) / (>=)"
echo "  >> if [ "$a" -ge "$b" ]"
echo "  >> if [ "$a" >= "$b" ]"
echo "  >> (("$a" >= "$b"))"
echo "- is less than (-lt) / (<)"
echo "  >> if [ "$a" -lt "$b" ]"
echo "  >> if [ "$a" < "$b" ]"
echo "  >> (("$a" < "$b"))"
echo "- is less than or equal to (-le) / (<=)"
echo "  >> if [ "$a" -le "$b" ]"
echo "  >> if [ "$a" <= "$b" ]"
echo "  >> (("$a" <= "$b"))"
echo
echo "--------------"
echo
echo "[*] String Comparison [*]"
echo
echo "- is equal to (=) / (==)"
echo "  >> if [ "$a" = "$b" ]"
echo "  >> if [ "$a" == "$b" ]"
echo "- is not equal to (!=)"
echo "  >> if [ "$a" != "$b" ]"
echo "- is less than, in ASCII alphabetical order (<)"
echo "  >> if [[ "$a" < "$b" ]]"
echo "- is greater than, in ASCII alphabetical order (>)"
echo "  >> if [[ "$a" > "$b" ]]"
echo "- string is null, has zero length (-z)"
echo "  >> if [ -z $a ]"
